package ml.karmaconfigs.LockLogin.Spigot.Utils.Files;

import ml.karmaconfigs.LockLogin.Lang;
import ml.karmaconfigs.LockLogin.Spigot.LockLoginSpigot;
import ml.karmaconfigs.LockLogin.WarningLevel;
import org.bukkit.configuration.file.YamlConfiguration;

import java.io.File;
import java.io.IOException;
import java.util.concurrent.TimeUnit;

/*
GNU LESSER GENERAL PUBLIC LICENSE
                       Version 2.1, February 1999

 Copyright (C) 1991, 1999 Free Software Foundation, Inc.
 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 Everyone is permitted to copy and distribute verbatim copies
 of this license document, but changing it is not allowed.

[This is the first released version of the Lesser GPL.  It also counts
 as the successor of the GNU Library Public License, version 2, hence
 the version number 2.1.]
 */

public final class ConfigGetter implements LockLoginSpigot {

    private final static File spigot = new File(plugin.getServer().getWorldContainer().getPath(), "spigot.yml");

    public ConfigGetter() {
        FileCreator creator = new FileCreator("config.yml", "config_spigot.yml");

        creator.createFile();
        creator.setDefaults();
        plugin.reloadConfig();
        plugin.saveConfig();

        plugin.reloadConfig();
    }

    public final boolean isBungeeCord() {
        if (spigot.exists()) {
            YamlConfiguration sp = YamlConfiguration.loadConfiguration(spigot);
            return sp.getBoolean("settings.bungeecord");
        } else {
            try {
                if (spigot.createNewFile()) {
                    out.Alert("LockLogin detected you are not running in spigot, so spigot.yml doesn't seems to exists, if your server.jar supports BungeeCord" +
                            " and you are using it, enable it in spigot.yml (Generated by LockLogin if it didn't exists)", WarningLevel.WARNING);
                } else {
                    out.Alert("An error occurred while trying to generate spigot.yml, (You won't be able to enable bungeecord mode)", WarningLevel.ERROR);
                }
                YamlConfiguration sp = YamlConfiguration.loadConfiguration(spigot);
                if (!sp.isSet("settings.bungeecord")) {
                    sp.set("settings.bungeecord", false);
                    try {
                        sp.save(spigot);
                    } catch (IOException e) {
                        out.Alert("Error while trying to save artificial spigot.yml to set bungeecord status", WarningLevel.ERROR);
                        out.Message("&c" + e.fillInStackTrace());
                    }
                }
                return sp.getBoolean("settings.bungeecord");
            } catch (IOException e) {
                out.Alert("Error while creating artificial spigot.yml to set bungeecord status", WarningLevel.ERROR);
                out.Message("&c" + e.fillInStackTrace());
                return false;
            }
        }
    }

    public final boolean isEnglish() {
        return getLang().equals(Lang.ENGLISH);
    }

    public final boolean isSpanish() {
        return getLang().equals(Lang.SPANISH);
    }

    public final boolean isSimplifiedChinese() {
        return getLang().equals(Lang.SIMPLIFIED_CHINESE);
    }

    public final boolean isItalian() {
        return getLang().equals(Lang.ITALIAN);
    }

    public final boolean isPolish() {
        return getLang().equals(Lang.POLISH);
    }

    public final boolean isFrench() {
        return getLang().equals(Lang.FRENCH);
    }

    public final boolean isCzech() {
        return getLang().equals(Lang.CZECH);
    }

    public final boolean langValid() {
        return isEnglish() || isSpanish() || isSimplifiedChinese() || isItalian() || isPolish() || isFrench() || isCzech();
    }

    public final Lang getLang() {
        String val = plugin.getConfig().getString("Lang", "en_EN");

        assert val != null;

        switch (val) {
            case "en_EN":
            case "english":
            case "English":
                return Lang.ENGLISH;
            case "es_ES":
            case "spanish":
            case "Spanish":
                return Lang.SPANISH;
            case "zh_CN":
            case "simplified_chinese":
            case "Simplified_chinese":
            case "Simplified_Chinese":
            case "simplified chinese":
            case "Simplified chinese":
            case "Simplified Chinese":
                return Lang.SIMPLIFIED_CHINESE;
            case "it_IT":
            case "italian":
            case "Italian":
                return Lang.ITALIAN;
            case "pl_PL":
            case "polish":
            case "Polish":
                return Lang.POLISH;
            case "fr_FR":
            case "french":
            case "French":
                return Lang.FRENCH;
            case "cz_CS":
            case "czech":
            case "Czech":
                return Lang.CZECH;
            default:
                return Lang.UNKNOWN;
        }
    }

    public final String FileSys() {
        return plugin.getConfig().getString("AccountSys");
    }

    public final boolean isYaml() {
        return FileSys().equalsIgnoreCase("File") || FileSys().equalsIgnoreCase("file");
    }

    public final boolean isMySQL() {
        if (!isBungeeCord()) {
            return FileSys().equalsIgnoreCase("MySQL") || FileSys().equalsIgnoreCase("mysql");
        } else {
            return false;
        }
    }

    public final boolean FileSysValid() {
        return isYaml() || isMySQL();
    }

    public final String ServerName() {
        return plugin.getConfig().getString("ServerName");
    }

    public final boolean RegisterBlind() {
        return plugin.getConfig().getBoolean("Register.Blind");
    }

    public final boolean RegisterNausea() {
        return plugin.getConfig().getBoolean("Register.Nausea");
    }

    public final int RegisterOut() {
        return plugin.getConfig().getInt("Register.TimeOut");
    }

    public final int MaxRegisters() {
        return plugin.getConfig().getInt("Register.Max");
    }

    public final boolean LoginBlind() {
        return plugin.getConfig().getBoolean("Login.Blind");
    }

    public final boolean LoginNausea() {
        return plugin.getConfig().getBoolean("Login.Nausea");
    }

    public final int LoginOut() {
        return plugin.getConfig().getInt("Login.TimeOut");
    }

    public final int GetMaxTries() {
        return plugin.getConfig().getInt("Login.MaxTries");
    }

    public final boolean AntiBot() {
        return plugin.getConfig().getBoolean("AntiBot");
    }

    public final boolean AllowSameIp() { return plugin.getConfig().getBoolean("AllowSameIp"); }

    public final boolean EnablePins() {
        return plugin.getConfig().getBoolean("Pin");
    }

    public final boolean CheckForUpdates() {
        return plugin.getConfig().getBoolean("Updater.Check");
    }

    public final int UpdateCheck() {
        if (plugin.getConfig().getInt("Updater.CheckTime") >= 5 && plugin.getConfig().getInt("Updater.CheckTime") <= 60) {
            return (int) TimeUnit.MINUTES.toSeconds(plugin.getConfig().getInt("Updater.CheckTime"));
        } else {
            plugin.getConfig().set("Updater.CheckTime", 5);
            return (int) TimeUnit.MINUTES.toSeconds(5);
        }
    }

    public final boolean ChangeLogs() {
        return plugin.getConfig().getBoolean("Updater.ChangeLog");
    }

    public final boolean UpdateSelf() {
        return plugin.getConfig().getBoolean("Updater.AutoUpdate");
    }

    public final boolean Enable2FA() {
        return plugin.getConfig().getBoolean("2FA");
    }

    public final boolean HandleSpawn() {
        return plugin.getConfig().getBoolean("Spawn.Manage");
    }

    public final boolean TakeBack() {
        return plugin.getConfig().getBoolean("Spawn.TakeBack");
    }

    public final boolean ClearChat() {
        return plugin.getConfig().getBoolean("ClearChat");
    }

    public final int AccountsPerIp() {
        return plugin.getConfig().getInt("AccountsPerIp");
    }

    public final boolean CheckNames() {
        return plugin.getConfig().getBoolean("CheckNames");
    }

    public final String BungeeProxy() {
        return plugin.getConfig().getString("BungeeProxy");
    }
}
